workflows:
- ./.github/workflows/*

github:
- any: ['./.github/**/*', '!./.github/workflows/*']

test:
- ./tests/**/*
- ./integration-tests/**/*

documentation:
- *.md
- ./images/**/*

source:
- ./src/**/*
- ./Lignator.sln
- ./.gitignore

environment:
- ./.vscode/*